## Ant Colony Optimizer

In [ ]:
import random
import numpy as np
def generateDistances(n_cities):
  cities = np.random.randint(3,51, size=(n_cities,n_cities))
  cities = (cities + cities.T)//2
  np.fill_diagonal(cities, 0)
  print(cities)
  return cities
def generatePheromones(n_cities):
  pheromones = np.zeros((n_cities,n_cities), dtype=int)
  print(pheromones)
  return pheromones
generateDistances(20)
generatePheromones(20)

[[ 0 16 24 41 18 39 35 14 44 30 26 42 30 17 28  8 35 32 42 24]
 [16  0 21 32  9 28 27 25 13 25 21 22 33 43 25 12 12 29 26 17]
 [24 21  0 27 18 33 33 20 28 43 28 29  7 21  9 19 19 31 45 34]
 [41 32 27  0 32 27 27 35 19 30 23 16 30 30  9 26 29 24 45 18]
 [18  9 18 32  0 32 25 22 35 41 25 21 35 18 17 27 28 22 24 21]
 [39 28 33 27 32  0  9 16 27 38 19 32 37 48 23 18 37 48 30 18]
 [35 27 33 27 25  9  0 15 25 25 32 17 35 43  8 27 19 36 37 41]
 [14 25 20 35 22 16 15  0 18 12 40 34 21 29 45 34 39 29 31 39]
 [44 13 28 19 35 27 25 18  0 22 17 45 25 36 25 29 37 37 29 24]
 [30 25 43 30 41 38 25 12 22  0 19 22 24 23 19 12 33 34 10 18]
 [26 21 28 23 25 19 32 40 17 19  0 24 22 27 11 15 42 29 37 46]
 [42 22 29 16 21 32 17 34 45 22 24  0 45 29 13 23 37 29 37 23]
 [30 33  7 30 35 37 35 21 25 24 22 45  0 29 33 24  9 32 27 33]
 [17 43 21 30 18 48 43 29 36 23 27 29 29  0 31 30 33 20 15 42]
 [28 25  9  9 17 23  8 45 25 19 11 13 33 31  0 34 39 12 14 37]
 [ 8 12 19 26 27 18 27 34 29 12 15 23 24 30 34  0 28 15

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0,

run on cities with diff # of ants, 1, 5, 10, 20
number of ants wont change in a run
a run consists of 50 iterations
each iteration is a full loop from start and back

In [ ]:
def calc_probability(cur)

In [ ]:
def move(current_city, cities, pheromones):
  min_cost = 0
  for i in range(cities.shape([0])):

    #calc th ecost using the formula


    path_cost = cities[current_city][i]
    if min_path == 0:
      min_path = path_cost
    else:
      if path_cost < min_path:
        min_path = path_cost

In [ ]:
def start_end(cities, n_ant, pheromones):
  start_pos = (0,0)
  visited_cities=[0]
  current_city= (0,0)
  total_cost = 0
  while current_city != start_pos
    next_city = move(current_city,visited_cities, cities, pheromones)
    total_cost += cities[current_city][next_city]
    visited_cities.append(next_city)
    current_city = next_city

  total_cost += cities[current_city][start_pos]
  visited_cities.append(start_pos)

  return visited_cities, total_cost

In [ ]:
def run(n_cities, n_ant, evaporation_rate):
  distances = generateDistances(n_cities)
  pheromones = generatePheromones(n_cities)
  # visited_cities=[]
  current_city= (0,0)
  min_path = 0
  optimum_path=[]
  for i in range(50): #from start to finish
    visited_cities, path_cost = start_end(distances, n_ant, pheromones)





    if min_path == 0:
      min_path = path_cost
    else:
      if path_cost < min_path:
        min_path = path_cost
        optimum_path = visited_cities
